<?php

/**
 * @file
 * Contains belholiday.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function belholiday_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the belholiday module.
    case 'help.page.belholiday':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Belarus holiday website') . '</p>';
      return $output;

    default:
  }
}
